on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸš€ Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node

      - name: ğŸ›’ Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v4

      - name: ğŸ“¦ Use Node.js
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: ğŸ§¶ Install Yarn
        if: ${{ steps.release.outputs.release_created }}
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: ğŸ—ï¸ Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: yarn install --frozen-lockfile

      - name: ğŸ‘· Build package
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build

      - name: ğŸ“¤ Publish package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
