on:
  push:
    branches:
      - main

name: ğŸš€ Release

jobs:
  release-please:
    name: ğŸ¤– Release Please
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ¤– Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: node

  release:
    name: ğŸš€ Release
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: ğŸ›’ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Environment
        uses: ./.github/actions/setup

      - name: ğŸ‘· Build package
        run: yarn build

      - name: ğŸ“¤ Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  test:
    name: ğŸ“Š Test Coverage
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: ğŸ›’ Checkout code
        uses: actions/checkout@v4

      - name: ğŸ”§ Setup Environment
        uses: ./.github/actions/setup

      - name: ğŸ§‘â€ğŸ”¬ Run tests and upload coverage
        uses: ./.github/actions/test
        with:
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
